version: '3.8'

services:
  app:
    container_name: consorcio-ai-pro
    build: .
    restart: always
    environment:
      # Conecta no host 'mysql' que est√° na mesma rede 'proxy' ou 'network_consorcioaipro'
      # Senha e Banco atualizados
      - DATABASE_URL=mysql://root:FO!t3oW6q(-im2Vw@mysql:3306/consorcio-ai-pro
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - network_phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consorcio-ai-pro.rule=Host(`${DOMAIN:-consorcioaipro.m2vendas.com.br}`)"
      - "traefik.http.routers.consorcio-ai-pro.entrypoints=websecure"
      - "traefik.http.routers.consorcio-ai-pro.tls.certresolver=myresolver"
      - "traefik.http.services.consorcio-ai-pro.loadbalancer.server.port=3000"

networks:
  network_phpmyadmin:
    external: true
